#!/bin/sh

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Mod4 T spawn foot

# Mod4+Q to close the focused view
riverctl map normal Mod4 Q close

# Mod4+R to open run menu
riverctl map normal Mod4 R spawn "tofi-run"

# Mod4+Shift+E to exit river
riverctl map normal Mod4+Shift Q exit

riverctl map normal Mod4 B spawn firefox

# Mod4+J and Mod4+K to focus the next/previous view in the layout stack
riverctl map normal Mod4 J focus-view next
riverctl map normal Mod4 K focus-view previous

# Mod4+Shift+J and Mod4+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Mod4+Shift J swap next
riverctl map normal Mod4+Shift K swap previous

# Mod4+Period and Mod4+Comma to focus the next/previous output
riverctl map normal Mod4 Period focus-output next
riverctl map normal Mod4 Comma focus-output previous

# Mod4+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Mod4+Shift Period send-to-output next
riverctl map normal Mod4+Shift Comma send-to-output previous

# Mod4+Return to bump the focused view to the top of the layout stack
riverctl map normal Mod4 Return zoom

# Mod4+H and Mod4+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Mod4 H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Mod4 L send-layout-cmd rivertile "main-ratio +0.05"

# Mod4+Shift+H and Mod4+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Mod4+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Mod4+Shift L send-layout-cmd rivertile "main-count -1"

# Mod4+Alt+{H,J,K,L} to move views
riverctl map normal Mod4+Alt H move left 100
riverctl map normal Mod4+Alt J move down 100
riverctl map normal Mod4+Alt K move up 100
riverctl map normal Mod4+Alt L move right 100

# Mod4+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Mod4+Alt+Control H snap left
riverctl map normal Mod4+Alt+Control J snap down
riverctl map normal Mod4+Alt+Control K snap up
riverctl map normal Mod4+Alt+Control L snap right

# Mod4+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Mod4+Alt+Shift H resize horizontal -100
riverctl map normal Mod4+Alt+Shift J resize vertical 100
riverctl map normal Mod4+Alt+Shift K resize vertical -100
riverctl map normal Mod4+Alt+Shift L resize horizontal 100

# Mod4 + Left Mouse Button to move views
riverctl map-pointer normal Mod4 BTN_LEFT move-view

# Mod4 + Right Mouse Button to resize views
riverctl map-pointer normal Mod4 BTN_RIGHT resize-view

# Mod4 + Middle Mouse Button to toggle float
riverctl map-pointer normal Mod4 BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod4+[1-9] to focus tag [0-8]
    riverctl map normal Mod4 $i set-focused-tags $tags

    # Mod4+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Mod4+Shift $i set-view-tags $tags
done

# Mod4+0 to focus all tags
# Mod4+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Mod4 0 set-focused-tags $all_tags
riverctl map normal Mod4+Shift 0 set-view-tags $all_tags

# Mod4+Space to toggle float
riverctl map normal Mod4 Space toggle-float

# Mod4+F to toggle fullscreen
riverctl map normal Mod4 F toggle-fullscreen

# Mod4+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Mod4 Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Mod4 Right send-layout-cmd rivertile "main-location right"
riverctl map normal Mod4 Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Mod4 Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod4+F11 to enter passthrough mode
riverctl map normal Mod4 F11 enter-mode passthrough

# Mod4+F11 to return to normal mode
riverctl map passthrough Mod4 F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

riverctl input 1133:16500 accel-profile none

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
riverctl spawn "pipewire"
riverctl spawn "wireplumber"
riverctl spawn "pipewire-pulse"
riverctl spawn "waybar -c .config/waybar/config -s .config/waybar/style.css"
riverctl spawn "swaybg -i Pictures/wallhaven-l8zmor.jpg"
