#!/bin/bash

WALLPAPER=$(basename $(ps aux | grep swaybg | awk '{if ($13 ~ /Pictures/) print $13}'))
FILES=$(ls ~/Pictures/wallpapers)
FILES=($FILES)
i=0
index=0
size=${#FILES[@]}
for FILE in ${FILES[@]}
do
    if [[ $FILE == $WALLPAPER ]]
    then
        index=$i
    fi
    (( i++ ))
done

((index--))
index=$(( index % size ))
WALLPAPER=${FILES[index]}

echo "set: $WALLPAPER"

pkill "swaybg"
riverctl spawn "swaybg -i Pictures/wallpapers/$WALLPAPER -m fill"
